/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAchievementsRouteImport } from './routes/student.achievements'
import { Route as StudentAiTutorRouteImport } from './routes/student.ai-tutor'
import { Route as StudentAssessmentsRouteImport } from './routes/student.assessments'
import { Route as StudentDiagnosticRouteImport } from './routes/student.diagnostic'
import { Route as StudentDishaRouteImport } from './routes/student.disha'
import { Route as StudentOnboardingRouteImport } from './routes/student.onboarding'
import { Route as StudentPracticeRouteImport } from './routes/student.practice'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentSubjectRouteImport } from './routes/student.subject'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAssessmentRouteImport } from './routes/teacher.assessment'
import { Route as TeacherAssessmentsRouteImport } from './routes/teacher.assessments'
import { Route as TeacherClassRouteImport } from './routes/teacher.class'
import { Route as TeacherGroupsRouteImport } from './routes/teacher.groups'
import { Route as StudentPracticeIndexRouteImport } from './routes/student.practice.index'
import { Route as StudentPracticePracticeIdRouteImport } from './routes/student.practice.$practiceId'
import { Route as StudentSubjectIndexRouteImport } from './routes/student.subject.index'
import { Route as StudentSubjectTopicRouteImport } from './routes/student.subject.$topic'
import { Route as TeacherStudentStudentIdRouteImport } from './routes/teacher.student.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAchievementsRoute = StudentAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiTutorRoute = StudentAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDiagnosticRoute = StudentDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDishaRoute = StudentDishaRouteImport.update({
  id: '/disha',
  path: '/disha',
  getParentRoute: () => StudentRoute,
} as any)
const StudentOnboardingRoute = StudentOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPracticeRoute = StudentPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSubjectRoute = StudentSubjectRouteImport.update({
  id: '/subject',
  path: '/subject',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssessmentRoute = TeacherAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssessmentsRoute = TeacherAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassRoute = TeacherClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGroupsRoute = TeacherGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentPracticeIndexRoute = StudentPracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentPracticeRoute,
} as any)
const StudentPracticePracticeIdRoute =
  StudentPracticePracticeIdRouteImport.update({
    id: '/$practiceId',
    path: '/$practiceId',
    getParentRoute: () => StudentPracticeRoute,
  } as any)
const StudentSubjectIndexRoute = StudentSubjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentSubjectRoute,
} as any)
const StudentSubjectTopicRoute = StudentSubjectTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => StudentSubjectRoute,
} as any)
const TeacherStudentStudentIdRoute = TeacherStudentStudentIdRouteImport.update({
  id: '/student/$studentId',
  path: '/student/$studentId',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/diagnostic': typeof StudentDiagnosticRoute
  '/student/disha': typeof StudentDishaRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/practice': typeof StudentPracticeRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/subject': typeof StudentSubjectRouteWithChildren
  '/teacher/assessment': typeof TeacherAssessmentRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/class': typeof TeacherClassRoute
  '/teacher/groups': typeof TeacherGroupsRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/practice/$practiceId': typeof StudentPracticePracticeIdRoute
  '/student/subject/$topic': typeof StudentSubjectTopicRoute
  '/teacher/student/$studentId': typeof TeacherStudentStudentIdRoute
  '/student/practice/': typeof StudentPracticeIndexRoute
  '/student/subject/': typeof StudentSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/diagnostic': typeof StudentDiagnosticRoute
  '/student/disha': typeof StudentDishaRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/assessment': typeof TeacherAssessmentRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/class': typeof TeacherClassRoute
  '/teacher/groups': typeof TeacherGroupsRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/practice/$practiceId': typeof StudentPracticePracticeIdRoute
  '/student/subject/$topic': typeof StudentSubjectTopicRoute
  '/teacher/student/$studentId': typeof TeacherStudentStudentIdRoute
  '/student/practice': typeof StudentPracticeIndexRoute
  '/student/subject': typeof StudentSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/diagnostic': typeof StudentDiagnosticRoute
  '/student/disha': typeof StudentDishaRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/practice': typeof StudentPracticeRouteWithChildren
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/subject': typeof StudentSubjectRouteWithChildren
  '/teacher/assessment': typeof TeacherAssessmentRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/class': typeof TeacherClassRoute
  '/teacher/groups': typeof TeacherGroupsRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/practice/$practiceId': typeof StudentPracticePracticeIdRoute
  '/student/subject/$topic': typeof StudentSubjectTopicRoute
  '/teacher/student/$studentId': typeof TeacherStudentStudentIdRoute
  '/student/practice/': typeof StudentPracticeIndexRoute
  '/student/subject/': typeof StudentSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/student/achievements'
    | '/student/ai-tutor'
    | '/student/assessments'
    | '/student/diagnostic'
    | '/student/disha'
    | '/student/onboarding'
    | '/student/practice'
    | '/student/profile'
    | '/student/progress'
    | '/student/subject'
    | '/teacher/assessment'
    | '/teacher/assessments'
    | '/teacher/class'
    | '/teacher/groups'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/student/practice/$practiceId'
    | '/student/subject/$topic'
    | '/teacher/student/$studentId'
    | '/student/practice/'
    | '/student/subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student/achievements'
    | '/student/ai-tutor'
    | '/student/assessments'
    | '/student/diagnostic'
    | '/student/disha'
    | '/student/onboarding'
    | '/student/profile'
    | '/student/progress'
    | '/teacher/assessment'
    | '/teacher/assessments'
    | '/teacher/class'
    | '/teacher/groups'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/student/practice/$practiceId'
    | '/student/subject/$topic'
    | '/teacher/student/$studentId'
    | '/student/practice'
    | '/student/subject'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/student/achievements'
    | '/student/ai-tutor'
    | '/student/assessments'
    | '/student/diagnostic'
    | '/student/disha'
    | '/student/onboarding'
    | '/student/practice'
    | '/student/profile'
    | '/student/progress'
    | '/student/subject'
    | '/teacher/assessment'
    | '/teacher/assessments'
    | '/teacher/class'
    | '/teacher/groups'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/student/practice/$practiceId'
    | '/student/subject/$topic'
    | '/teacher/student/$studentId'
    | '/student/practice/'
    | '/student/subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/achievements': {
      id: '/student/achievements'
      path: '/achievements'
      fullPath: '/student/achievements'
      preLoaderRoute: typeof StudentAchievementsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-tutor': {
      id: '/student/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/student/ai-tutor'
      preLoaderRoute: typeof StudentAiTutorRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/diagnostic': {
      id: '/student/diagnostic'
      path: '/diagnostic'
      fullPath: '/student/diagnostic'
      preLoaderRoute: typeof StudentDiagnosticRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/disha': {
      id: '/student/disha'
      path: '/disha'
      fullPath: '/student/disha'
      preLoaderRoute: typeof StudentDishaRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/onboarding': {
      id: '/student/onboarding'
      path: '/onboarding'
      fullPath: '/student/onboarding'
      preLoaderRoute: typeof StudentOnboardingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/practice': {
      id: '/student/practice'
      path: '/practice'
      fullPath: '/student/practice'
      preLoaderRoute: typeof StudentPracticeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/subject': {
      id: '/student/subject'
      path: '/subject'
      fullPath: '/student/subject'
      preLoaderRoute: typeof StudentSubjectRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assessment': {
      id: '/teacher/assessment'
      path: '/assessment'
      fullPath: '/teacher/assessment'
      preLoaderRoute: typeof TeacherAssessmentRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assessments': {
      id: '/teacher/assessments'
      path: '/assessments'
      fullPath: '/teacher/assessments'
      preLoaderRoute: typeof TeacherAssessmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/class': {
      id: '/teacher/class'
      path: '/class'
      fullPath: '/teacher/class'
      preLoaderRoute: typeof TeacherClassRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/groups': {
      id: '/teacher/groups'
      path: '/groups'
      fullPath: '/teacher/groups'
      preLoaderRoute: typeof TeacherGroupsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/practice/': {
      id: '/student/practice/'
      path: '/'
      fullPath: '/student/practice/'
      preLoaderRoute: typeof StudentPracticeIndexRouteImport
      parentRoute: typeof StudentPracticeRoute
    }
    '/student/practice/$practiceId': {
      id: '/student/practice/$practiceId'
      path: '/$practiceId'
      fullPath: '/student/practice/$practiceId'
      preLoaderRoute: typeof StudentPracticePracticeIdRouteImport
      parentRoute: typeof StudentPracticeRoute
    }
    '/student/subject/': {
      id: '/student/subject/'
      path: '/'
      fullPath: '/student/subject/'
      preLoaderRoute: typeof StudentSubjectIndexRouteImport
      parentRoute: typeof StudentSubjectRoute
    }
    '/student/subject/$topic': {
      id: '/student/subject/$topic'
      path: '/$topic'
      fullPath: '/student/subject/$topic'
      preLoaderRoute: typeof StudentSubjectTopicRouteImport
      parentRoute: typeof StudentSubjectRoute
    }
    '/teacher/student/$studentId': {
      id: '/teacher/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/teacher/student/$studentId'
      preLoaderRoute: typeof TeacherStudentStudentIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface ParentRouteChildren {
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentPracticeRouteChildren {
  StudentPracticePracticeIdRoute: typeof StudentPracticePracticeIdRoute
  StudentPracticeIndexRoute: typeof StudentPracticeIndexRoute
}

const StudentPracticeRouteChildren: StudentPracticeRouteChildren = {
  StudentPracticePracticeIdRoute: StudentPracticePracticeIdRoute,
  StudentPracticeIndexRoute: StudentPracticeIndexRoute,
}

const StudentPracticeRouteWithChildren = StudentPracticeRoute._addFileChildren(
  StudentPracticeRouteChildren,
)

interface StudentSubjectRouteChildren {
  StudentSubjectTopicRoute: typeof StudentSubjectTopicRoute
  StudentSubjectIndexRoute: typeof StudentSubjectIndexRoute
}

const StudentSubjectRouteChildren: StudentSubjectRouteChildren = {
  StudentSubjectTopicRoute: StudentSubjectTopicRoute,
  StudentSubjectIndexRoute: StudentSubjectIndexRoute,
}

const StudentSubjectRouteWithChildren = StudentSubjectRoute._addFileChildren(
  StudentSubjectRouteChildren,
)

interface StudentRouteChildren {
  StudentAchievementsRoute: typeof StudentAchievementsRoute
  StudentAiTutorRoute: typeof StudentAiTutorRoute
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentDiagnosticRoute: typeof StudentDiagnosticRoute
  StudentDishaRoute: typeof StudentDishaRoute
  StudentOnboardingRoute: typeof StudentOnboardingRoute
  StudentPracticeRoute: typeof StudentPracticeRouteWithChildren
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentSubjectRoute: typeof StudentSubjectRouteWithChildren
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAchievementsRoute: StudentAchievementsRoute,
  StudentAiTutorRoute: StudentAiTutorRoute,
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentDiagnosticRoute: StudentDiagnosticRoute,
  StudentDishaRoute: StudentDishaRoute,
  StudentOnboardingRoute: StudentOnboardingRoute,
  StudentPracticeRoute: StudentPracticeRouteWithChildren,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentSubjectRoute: StudentSubjectRouteWithChildren,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAssessmentRoute: typeof TeacherAssessmentRoute
  TeacherAssessmentsRoute: typeof TeacherAssessmentsRoute
  TeacherClassRoute: typeof TeacherClassRoute
  TeacherGroupsRoute: typeof TeacherGroupsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherStudentStudentIdRoute: typeof TeacherStudentStudentIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssessmentRoute: TeacherAssessmentRoute,
  TeacherAssessmentsRoute: TeacherAssessmentsRoute,
  TeacherClassRoute: TeacherClassRoute,
  TeacherGroupsRoute: TeacherGroupsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherStudentStudentIdRoute: TeacherStudentStudentIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
